import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/trip_plan.dart';

class PdfService {
  Future<void> exportItineraryToPdf(TripPlan plan) async {
    final pdf = pw.Document();

    final content = plan.generatedItinerary;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    '${plan.destination} - ${plan.duration} Days',
                    style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
                  ),
                  pw.SizedBox(height: 8),
                  pw.Text('Travel Style: ${plan.travelStyle} | Budget: ${plan.budget}'),
                  pw.SizedBox(height: 16),
                  pw.Divider(),
                ],
              ),
            ),
            pw.SizedBox(height: 16),
            pw.Text(content),
            pw.SizedBox(height: 32),
            pw.Divider(),
            pw.SizedBox(height: 8),
            pw.Center(
              child: pw.Text(
                'Generated by AI Travel Planner',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
              ),
            ),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: '${plan.destination}_Itinerary.pdf',
    );
  }
}
