import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:flutter_animate/flutter_animate.dart';
import '../providers/travel_provider.dart';
import '../models/trip_plan.dart';
import '../widgets/loading_overlay.dart';
import 'chat_screen.dart';

class TripFormScreen extends StatefulWidget {
  const TripFormScreen({super.key});

  @override
  State<TripFormScreen> createState() => _TripFormScreenState();
}

class _TripFormScreenState extends State<TripFormScreen> {
  final _formKey = GlobalKey<FormState>();
  
  final _destinationController = TextEditingController();
  final _specialRequestsController = TextEditingController();
  
  double _duration = 7;
  String _selectedBudget = '💰 Budget';
  String _selectedTravelStyle = '🏖️ Relaxation';
  String _selectedTravelers = '🧍 Solo';

  final _budgetOptions = ['💰 Budget', '💎 Mid-Range', '👑 Luxury'];
  final _styleOptions = ['🏔️ Adventure', '🏛️ Cultural', '🏖️ Relaxation', '🍜 Foodie', '🛍️ Shopping'];
  final _travelersOptions = ['🧍 Solo', '👫 Couple', '👨‍👩‍👧 Family', '👥 Group'];

  @override
  void dispose() {
    _destinationController.dispose();
    _specialRequestsController.dispose();
    super.dispose();
  }

  Future<void> _generateItinerary() async {
    if (!_formKey.currentState!.validate()) return;
    
    // Dismiss keyboard
    FocusScope.of(context).unfocus();

    // Show loading overlay
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (BuildContext context) {
        return const LoadingOverlay(message: 'Gemini is crafting\nyour perfect trip...');
      },
    );

    final plan = TripPlan(
      id: '', // Generated by provider
      title: 'Trip to ${_destinationController.text.trim()}',
      destination: _destinationController.text.trim(),
      duration: _duration.toInt(),
      budget: _selectedBudget,
      travelStyle: _selectedTravelStyle,
      travelers: _selectedTravelers,
      specialRequests: _specialRequestsController.text.trim(),
      generatedItinerary: '',
      messages: [],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    final provider = Provider.of<TravelProvider>(context, listen: false);
    
    try {
      await provider.startNewTrip(plan);
      
      if (!mounted) return;
      
      // Hide loading overlay
      Navigator.of(context).pop();

      if (provider.errorMessage == null) {
        Navigator.pushReplacement(
          context,
          MaterialPageRoute(builder: (_) => const ChatScreen()),
        );
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(provider.errorMessage!),
            backgroundColor: Colors.red,
          ),
        );
      }
    } catch (e) {
      if (!mounted) return;
      Navigator.of(context).pop();
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Failed to generate trip: $e'),
          backgroundColor: Colors.red,
        ),
      );
    }
  }

  Widget _buildSectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 16.0),
      child: Text(
        title,
        style: Theme.of(context).textTheme.titleLarge?.copyWith(
          fontWeight: FontWeight.bold,
          color: const Color(0xFFF4A825),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Design Your Adventure'),
        centerTitle: true,
      ),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(24.0),
          children: [
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildSectionTitle('Where do you want to go?'),
                TextFormField(
                  controller: _destinationController,
                  decoration: const InputDecoration(
                    hintText: 'e.g. Paris, France or Bali, Indonesia',
                    prefixIcon: Icon(Icons.place),
                  ),
                  validator: (value) => value == null || value.trim().isEmpty ? 'Destination is required' : null,
                ),
              ],
            ).animate().fadeIn(duration: 400.ms).slideX(begin: -0.1, end: 0, duration: 400.ms),
            
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildSectionTitle('Duration: ${_duration.toInt()} Days'),
                Slider(
                  value: _duration,
                  min: 1,
                  max: 30,
                  divisions: 29,
                  activeColor: const Color(0xFFF4A825),
                  label: '${_duration.toInt()} Days',
                  onChanged: (value) {
                    setState(() => _duration = value);
                  },
                ),
              ],
            ).animate().fadeIn(delay: 100.ms, duration: 400.ms).slideX(begin: -0.1, end: 0, duration: 400.ms),

            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildSectionTitle('Budget'),
                Wrap(
                  spacing: 8.0,
                  runSpacing: 8.0,
                  children: _budgetOptions.map((option) {
                    return ChoiceChip(
                      label: Text(option),
                      selected: _selectedBudget == option,
                      selectedColor: const Color(0xFFF4A825),
                      backgroundColor: const Color(0xFF152847),
                      labelStyle: TextStyle(
                        color: _selectedBudget == option ? const Color(0xFF0A1628) : Colors.white,
                        fontWeight: _selectedBudget == option ? FontWeight.bold : FontWeight.normal,
                      ),
                      onSelected: (selected) {
                        if (selected) setState(() => _selectedBudget = option);
                      },
                    );
                  }).toList(),
                ),
              ],
            ).animate().fadeIn(delay: 200.ms, duration: 400.ms).slideX(begin: -0.1, end: 0, duration: 400.ms),

            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildSectionTitle('Travel Style'),
                Wrap(
                  spacing: 8.0,
                  runSpacing: 8.0,
                  children: _styleOptions.map((option) {
                    return ChoiceChip(
                      label: Text(option),
                      selected: _selectedTravelStyle == option,
                      selectedColor: const Color(0xFFF4A825),
                      backgroundColor: const Color(0xFF152847),
                      labelStyle: TextStyle(
                        color: _selectedTravelStyle == option ? const Color(0xFF0A1628) : Colors.white,
                        fontWeight: _selectedTravelStyle == option ? FontWeight.bold : FontWeight.normal,
                      ),
                      onSelected: (selected) {
                        if (selected) setState(() => _selectedTravelStyle = option);
                      },
                    );
                  }).toList(),
                ),
              ],
            ).animate().fadeIn(delay: 300.ms, duration: 400.ms).slideX(begin: -0.1, end: 0, duration: 400.ms),

            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildSectionTitle('Travelers'),
                Wrap(
                  spacing: 8.0,
                  runSpacing: 8.0,
                  children: _travelersOptions.map((option) {
                    return ChoiceChip(
                      label: Text(option),
                      selected: _selectedTravelers == option,
                      selectedColor: const Color(0xFFF4A825),
                      backgroundColor: const Color(0xFF152847),
                      labelStyle: TextStyle(
                        color: _selectedTravelers == option ? const Color(0xFF0A1628) : Colors.white,
                        fontWeight: _selectedTravelers == option ? FontWeight.bold : FontWeight.normal,
                      ),
                      onSelected: (selected) {
                        if (selected) setState(() => _selectedTravelers = option);
                      },
                    );
                  }).toList(),
                ),
              ],
            ).animate().fadeIn(delay: 400.ms, duration: 400.ms).slideX(begin: -0.1, end: 0, duration: 400.ms),

            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildSectionTitle('Special Requests (Optional)'),
                TextFormField(
                  controller: _specialRequestsController,
                  maxLines: 3,
                  decoration: const InputDecoration(
                    hintText: 'Any dietary needs, accessibility requirements, must-see places...',
                  ),
                ),
              ],
            ).animate().fadeIn(delay: 500.ms, duration: 400.ms).slideX(begin: -0.1, end: 0, duration: 400.ms),
            
            const SizedBox(height: 48),
            
            SizedBox(
              height: 56,
              child: ElevatedButton.icon(
                onPressed: _generateItinerary,
                icon: const Icon(Icons.auto_awesome),
                label: const Text('Generate My Itinerary ✨', style: TextStyle(fontSize: 16)),
              ),
            ).animate().fadeIn(delay: 600.ms, duration: 400.ms).scale(begin: const Offset(0.9, 0.9), end: const Offset(1, 1)),
            
            const SizedBox(height: 48),
          ],
        ),
      ),
    );
  }
}
